name: diagram-extraction-model
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip:
    - ultralytics
    - opencv-python
    - supervision
    - roboflow
    - numpy
    - pillow 